# fly.toml app configuration file generated for lively-frost-5830 on 2023-06-24T19:05:33+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-frost-5830"
primary_region = "ams"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
