# Generated by Django 4.2.2 on 2023-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgreeting',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='chat ID'),
        ),
    ]
